chore(types): work around TS2775
test/utils.test.js:156:3 - error TS2775: Assertions require every name in the call target to be declared with an explicit type annotation.

156   assertAllDefined(foo);
      ~~~~~~~~~~~~~~~~

  src/ses-utils.ts:141:14
    141 export const assertAllDefined = <T extends Record<string, unknown>>(
                     ~~~~~~~~~~~~~~~~
    'assertAllDefined' needs an explicit type annotation.