controller: give same HandledPromise to all compartments
We need this to make sure anyone who imports `@agoric/eventual-send` uses the
shared HandledPromise rather than trying to build their own, which causes
errors in E(presence).foo() (in particular it triggers the "throw TypeError
... is not a function", in the `forwardingHandler.applyMethod /
makeForwarder` clause towards the end of eventual-send/src/index.js).