chore(deps): pin types/node
22.13.4 had some bug causing:

../internal/src/node/fs-stream.js(39,12): error TS2349: This expression is not callable.
  Each member of the union type '{ (event: string, listener: (...args: any[]) => void): Socket; (event: "close", listener: (hadError: boolean) => void): Socket; (event: "connect", listener: () => void): Socket; (event: "connectionAttempt", listener: (ip: string, port: number, family: number) => void): Socket; (event: "connectionAttemptFailed", list...' has signatures, but none of those signatures are compatible with each other.
../internal/src/node/fs-stream.js(40,12): error TS2349: This expression is not callable.
  Each member of the union type '{ (event: string, listener: (...args: any[]) => void): Socket; (event: "close", listener: (hadError: boolean) => void): Socket; (event: "connect", listener: () => void): Socket; (event: "connectionAttempt", listener: (ip: string, port: number, family: number) => void): Socket; (event: "connectionAttemptFailed", list...' has signatures, but none of those signatures are compatible with each other.