feat(inter-protocol): Add core-eval builder for depositing reserve withdrawal invitations (#11678)
Ref https://github.com/Agoric/product-tasks/issues/274
Ref #11460

## Description
Given a destination address, deposits a one-shot reserve withdrawal invitation in the corresponding smart wallet (or optionally more than one).

### Security Considerations
The ability to withdraw from the reserve must obviously be closely held. This leverages the existing bootstrap vat core-eval protections and requires a specific destination address.

### Scaling Considerations
n/a

### Documentation Considerations
None special.

### Testing Considerations

<details><summary>Verified locally with the inquisitor</summary>

```console
$ agoric run scripts/inter-protocol/withdraw-reserve.build.js --address agoric18lfz3w97u72p4jq58gdn05ftdcv9rwz0ft5l2m --count 3
agoric: run: running …/agoric-sdk/packages/builders/scripts/inter-protocol/withdraw-reserve.build.js
creating withdraw-reserve-permit.json
creating withdraw-reserve.js
You can now run a governance submission command like:
  agd tx gov submit-proposal swingset-core-eval withdraw-reserve-permit.json withdraw-reserve.js \
    --title="Enable <something>" --description="Evaluate withdraw-reserve.js" --deposit=1000000ubld \
    --gas=auto --gas-adjustment=1.2
Remember to install bundles before submitting the proposal:
  agd tx swingset install-bundle @/home/rgibson/.agoric/cache/b1-d32f06015ee41ddfede6f029a3a602b1288463a9f0ff1af99e614a443b40cba493d3c7e776b3ce5b81b5f61814462db9307b84e0cf7fe5ef404ef61b2ea6eb38.json

$ packages/cosmic-swingset/tools/inquisitor.mjs packages/cosmic-swingset/t1/n0/data/agoric/swingstore.sqlite
Loading slog sender modules: @agoric/telemetry/src/flight-recorder.js
Launching SwingSet kernel
buildSwingset
[bridge] received { args: [ 'highPriorityQueue.tail' ], method: 'get' }
[bridge] received { args: [ 'highPriorityQueue.head' ], method: 'get' }
[bridge] received { args: [ 'actionQueue.tail' ], method: 'get' }
[bridge] received { args: [ 'actionQueue.head' ], method: 'get' }
Launched SwingSet kernel
endowments: kvStore swingStore getLastBlockInfo pushQueueRecord pushCoreEval runNextBlock EV controller krefOf kser kslot kunser mutations runCoreEval stable
endowments.stable: db getRefs kvGet kvGetJSON kvGlob scanVatStore vatsByID vatsByName
> bundle = JSON.parse(require("fs").readFileSync("/home/rgibson/.agoric/cache/b1-d32f06015ee41ddfede6f029a3a602b1288463a9f0ff1af99e614a443b40cba493d3c7e776b3ce5b81b5f61814462db9307b84e0cf7fe5ef404ef61b2ea6eb38.json", "utf8"));
…
> await controller.validateAndInstallBundle(bundle);
…
> coreEvalSrc = require("fs").readFileSync("./withdraw-reserve.js", "utf8");
…
> permits = JSON.parse( require("fs").readFileSync("./withdraw-reserve-permit.json", "utf8") );
…
> await runCoreEval(coreEvalSrc, permits);
evaluateBundleCap { manifestBundleRef: { bundleID: 'b1-d32f06015ee41ddfede6f029a3a602b1288463a9f0ff1af99e614a443b40cba493d3c7e776b3ce5b81b5f61814462db9307b84e0cf7fe5ef404ef61b2ea6eb38' }, manifestGetterName: 'getManifestForInviteWithdrawer', vatAdminSvc: Promise [Promise] {} }
execute { manifestGetterName: 'getManifestForInviteWithdrawer', bundleExports: [ 'getManifestForInviteWithdrawer', 'inviteReserveWithdrawer' ] }
coreProposal: inviteReserveWithdrawer
Logging sent error stack (TypeError#1)
TypeError#1: target has no method getLimitedCreatorFacet , has [ '__getInterfaceGuard__', '__getMethodNames__', 'addIssuer', 'getAllocations', 'makeRepeatableWithdrawalInvitation', 'makeShortfallReportingInvitation', 'makeSingleWithdrawalInvitation', 'revokeOutstandingWithdrawalInvitations' ]
TypeError: target has no method "getLimitedCreatorFacet", has ["__getInterfaceGuard__","__getMethodNames__","addIssuer","getAllocations","makeRepeatableWithdrawalInvitation","makeShortfallReportingInvitation","makeSingleWithdrawalInvitation","revokeOutstandingWithdrawalInvitations"]
 at makeError (/bundled-source/.../ses/src/error/assert.js:352)
 at fail (/bundled-source/.../ses/src/error/assert.js:482)
 at localApplyMethod (/bundled-source/.../eventual-send/src/local.js:118)
 at apply ()
 at dispatchToHandler (/bundled-source/.../eventual-send/src/handled-promise.js:159)
 at win (/bundled-source/.../eventual-send/src/handled-promise.js:514)
 at ()

TypeError#1 ERROR_NOTE: Sent as error:liveSlots:v39#70001
----- InviteReserveWithdrawer.2  2 Failed to get limited creator facet: (RemoteTypeError(error:liveSlots:v39#70001)#1)
RemoteTypeError(error:liveSlots:v39#70001)#1: target has no method "getLimitedCreatorFacet", has ["__getInterfaceGuard__","__getMethodNames__","addIssuer","getAllocations","makeRepeatableWithdrawalInvitation","makeShortfallReportingInvitation","makeSingleWithdrawalInvitation","revokeOutstandingWithdrawalInvitations"]
TypeError: target has no method "getLimitedCreatorFacet", has ["__getInterfaceGuard__","__getMethodNames__","addIssuer","getAllocations","makeRepeatableWithdrawalInvitation","makeShortfallReportingInvitation","makeSingleWithdrawalInvitation","revokeOutstandingWithdrawalInvitations"]
 at makeError (/bundled-source/.../ses/src/error/assert.js:352)
 at decodeErrorCommon (/bundled-source/.../marshal/src/marshal.js:308)
 at decodeFromSmallcaps (/bundled-source/.../marshal/src/encodeToSmallcaps.js:440)
 at fromCapData (/bundled-source/.../marshal/src/marshal.js:397)
 at notifyOnePromise (/bundled-source/.../swingset-liveslots/src/liveslots.js:1045)
 at notify (/bundled-source/.../swingset-liveslots/src/liveslots.js:1069)
 at dispatchToUserspace (/bundled-source/.../swingset-liveslots/src/liveslots.js:1338)
 at runWithoutMetering (/bundled-source/.../swingset-xsnap-supervisor/lib/supervisor-subprocess-xsnap.js:59)
 at ()

awaiting depositFacet for reserve withdrawer agoric18lfz3w97u72p4jq58gdn05ftdcv9rwz0ft5l2m
awaiting depositFacet for reserve withdrawer agoric18lfz3w97u72p4jq58gdn05ftdcv9rwz0ft5l2m
awaiting depositFacet for reserve withdrawer agoric18lfz3w97u72p4jq58gdn05ftdcv9rwz0ft5l2m
```

</details>

### Upgrade Considerations
To be executed by a standalone core-eval proposal.