feat(demo-signing): sign and broadcast WalletAction
without ledger

 - toward keplr/ledger demo: copy SuggestChain.js
 - sign simple msg/doc with keplr/ledger (WIP)
   - ISSUE: started with cosmjs API integration but
     couldn't get it to work without skipping it
 - chore(demo-signing): figured out offlignSigner.signAmino() API
   no longer skipping all the way to keplr.signAmino()
 - feat(demo-signing): sign WALLET_ACTION with keplr, ledger
 - send signed transaction to chain (WIP)
   - can connect to chain and query for sequence
   - aminoTypes seem to work
   - TODO: generate protobuf codec for MsgWalletAction
 - pass connectWithSigner authority explicitly
 - integrate MsgWalletAction proto stub via registry
 - MsgWalletAction.owner is bytes, not string

provide enough gas

avoid:

Error: Broadcasting transaction failed with code 11 (codespace: sdk). Log: out of gas in location: ReadFlat; gasWanted: 250, gasUsed: 1000: out of gas
    at SigningStargateClient.broadcastTx (stargateclient.ts:413:9)
    at async HTMLButtonElement.<anonymous> (keplr-ledger-demo.js:215:16)