fix(orchestrate): makeStateRecord type annotation
error TS2741: Property 'account' is missing in type '{}' but required in type '{ account: OrchestrationAccount<any> | undefined; }'