test(liqidator): zcfSeat bug snapshot
 - run.make(qty) abbreviates AmountMath.make(run, qty * 1000_000n)
   - run.make(qty, exp) abbreviates AmountMath.make(run, qty * 10n **
     exp)
   - likewise atom.make(qty) with default 10_000 (decimalPlaces: 4)
   - avoid using BASIS_POINT as a scale factor outside ratios
 - initial liquidity: meant 200k:10k but got 200k:1000k
 - use makeDriver to set initial price to 12_34 (not sure about this)
   - not sure about priceBase
 - vote to raise DebtLimit for ATOM to 10M RUN
 - use actual numbers for big AMM trade (WIP)
   fails with 'Seat ("[Alleged: zcfSeat]") was already an argument to
   reallocate'

~/projects/agoric/agoric-sdk/packages/run-protocol
08:15 connolly@jambox$ yarn test test/vaultFactory/test-liquidator.js -m 'case 5513'
yarn run v1.22.17
$ ava test/vaultFactory/test-liquidator.js -m 'case 5513'

./bundles/ bundle-faucet.js valid: 92 files bundled at 2022-06-06T12:04:55.718Z
./bundles/ bundle-liquidateIncrementally.js valid: 93 files bundled at 2022-06-06T12:04:55.722Z
./bundles/ bundle-VaultFactory.js valid: 128 files bundled at 2022-06-06T12:04:55.718Z
./bundles/ bundle-amm.js valid: 132 files bundled at 2022-06-06T12:04:55.254Z
./bundles/ bundle-reserve.js valid: 114 files bundled at 2022-06-06T12:04:55.722Z
Saved issuer Object [Alleged: aEth issuer] {} to keyword Aeth and got back Object [Alleged: aEth issuer] {}
----- Reserve.2  2 addIssuerFromAmm {
  ammSecondaryBrand: Object [Alleged: aEth brand] {},
  keyword: 'RaEth'
}
{ issuer: Object [Alleged: aEth issuer] {} }
----- Reserve.2  3 addIssuer { brand: Object [Alleged: aEth brand] {}, keyword: 'RaEth' }
----- Reserve.2  4 addIssuer storing { keyword: 'RaEth', brand: Object [Alleged: aEth brand] {} }
----- XykAmm.2  2 handlePoolAdded {
  secondaryBrand: Object [Alleged: aEth brand] {},
  liquidityKeyword: 'AethLiquidity'
}
----- XykAmm.2  3 ensuring reserve has the liquidity issuer {
  secondaryBrand: Object [Alleged: aEth brand] {},
  secondaryIssuer: Object [Alleged: aEth issuer] {}
}
----- Reserve.2  5 addLiquidityIssuer {
  baseBrand: Object [Alleged: aEth brand] {},
  baseKeyword: 'RaEth',
  liquidityBrand: Object [Alleged: AethLiquidity brand] {
    isMyIssuer: [Function: isMyIssuer],
    getAllegedName: [Function: getAllegedName],
    getDisplayInfo: [Function: getDisplayInfo]
  },
  liquidityKeyword: 'RaEthLiquidity'
}
----- XykAmm.2  4 move AethLiquidity to the reserve {
  AethLiquidity: {
    brand: Object [Alleged: AethLiquidity brand] {
      isMyIssuer: [Function: isMyIssuer],
      getAllegedName: [Function: getAllegedName],
      getDisplayInfo: [Function: getDisplayInfo]
    },
    value: 1000n
  }
}
----- Reserve.2  6 received collateral {
  brand: Object [Alleged: AethLiquidity brand] {
    isMyIssuer: [Function: isMyIssuer],
    getAllegedName: [Function: getAllegedName],
    getDisplayInfo: [Function: getDisplayInfo]
  },
  value: 1000n
}
----- XykAmm.2  5 handlePoolAdded deposited {
  AethLiquidity: {
    brand: Object [Alleged: AethLiquidity brand] {
      isMyIssuer: [Function: isMyIssuer],
      getAllegedName: [Function: getAllegedName],
      getDisplayInfo: [Function: getDisplayInfo]
    },
    value: 0n
  }
}
----- XykAmm.2  6 handlePoolAdded done
TEST ONLY: capturing test data [Function (anonymous)]
----- PV.3  2 addVault undefined f8000000000000000:1
----- PV.3  3 removeVault f8000000000000000:1 f8000000000000000:1
----- PV.3  4 addVault undefined fc03c924924924925:1
Temporary logging of sent error (Error#1)
Error#1: Seat ( Object [Alleged: zcfSeat] {
  getNotifier: [Function: getNotifier],
  getProposal: [Function: getProposal],
  exit: [Function: exit],
  fail: [Function: fail],
  hasExited: [Function: hasExited],
  getAmountAllocated: [Function: getAmountAllocated],
  getCurrentAllocation: [Function: getCurrentAllocation],
  getStagedAllocation: [Function: getStagedAllocation],
  isOfferSafe: [Function: isOfferSafe],
  incrementBy: [Function: incrementBy],
  decrementBy: [Function: decrementBy],
  clear: [Function: clear],
  hasStagedAllocation: [Function: hasStagedAllocation]
} ) was already an argument to reallocate
  at eval (.../zoe/src/contractFacet/zcfSeat.js:188:1)
  at Array.forEach (<anonymous>)
  at Alleged: zcf.reallocate (.../zoe/src/contractFacet/zcfSeat.js:183:7)
  at Alleged: double pool.allocateGainsAndLosses (.../run-protocol/src/vpool-xyk-amm/doublePool.js:64:5)
  at swapIn (.../run-protocol/src/vpool-xyk-amm/swap.js:44:13)
  at eval (.../marshal/src/make-far.js:167:31)

Error#1 ERROR_NOTE: Thrown from: (Error#2) : 802 . 0
Error#1 ERROR_NOTE: Rejection from: (Error#3) : 809 . 0
Error#1 ERROR_NOTE: Sent as error:captp:far-zoeTest#20001
Nested 2 errors under Error#1
  Error#2: Event: 801.1
    at Object.apply (.../eventual-send/src/E.js:36:23)
    at Alleged: handleOfferObj.handleOffer (.../zoe/src/contractFacet/zcfZygote.js:328:35)

  Error#2 ERROR_NOTE: Caused by: (Error#4)
  Nested error under Error#2
    Error#4: Event: 800.1
      at Alleged: instanceAdmin.makeUserSeat (packages/zoe/src/zoeService/startInstance.js:138:14)
      at Alleged: zoeService.offer (packages/zoe/src/zoeService/offer/offer.js:62:42)

  Error#3: Event: 808.1
  Error: Event: 808.1

  Error#3 ERROR_NOTE: Caused by: (Error#5)
  Nested error under Error#3
    Error#5: Event: 805.2
      at Object.sellOnAMM (packages/run-protocol/test/vaultFactory/test-liquidator.js:500:49)
      at async packages/run-protocol/test/vaultFactory/test-liquidator.js:977:3

CapTP near-zoeTest exception: (RemoteError(error:captp:far-zoeTest#20001)#6)
RemoteError(error:captp:far-zoeTest#20001)#6: Seat ("[Alleged: zcfSeat]") was already an argument to reallocate
Error: Seat ("[Alleged: zcfSeat]") was already an argument to reallocate

RemoteError(error:captp:far-zoeTest#20001)#6 ERROR_NOTE: Rejection from: (Error#5) : 808 . 1
Nested error under RemoteError(error:captp:far-zoeTest#20001)#6
REJECTED from ava test: (RemoteError(error:captp:far-zoeTest#20001)#6)
  case 5513

    ℹ ----- TestST.4  3 faucet {
        runInitialLiquidity: {
          brand: Object @Alleged: RUN brand {},
          value: 200000000000n,
        },
        runPayment: Object @Alleged: RUN payment {},
      }
    ℹ ----- TestST.4  4 amm {
        ammFacets: {
          ammCreatorFacet: Object @Alleged: governedContract creator facet {},
          ammLiquidity: Promise {},
          ammPublicFacet: Object @Alleged: publicFacet {},
          instance: Promise {},
        },
      }
    ℹ && task was past its deadline when scheduled: 0 &&
    ℹ @@ schedule task for:2, currently: 0 @@
    ℹ ----- TestST.4  5 pa {
        governorInstance: Object @Alleged: InstanceHandle {},
        lender: Object @Alleged: VaultDirector public {},
        priceAuthority: Object @Alleged: PriceAuthority {
          getQuoteIssuer: Function getQuoteIssuer {},
          getTimerService: Function getTimerService {},
          makeQuoteNotifier: Function makeQuoteNotifier {},
          mutableQuoteWhenGT: AsyncFunction {},
          mutableQuoteWhenGTE: AsyncFunction {},
          mutableQuoteWhenLT: AsyncFunction {},
          mutableQuoteWhenLTE: AsyncFunction {},
          quoteAtTime: AsyncFunction {},
          quoteGiven: AsyncFunction {},
          quoteWanted: AsyncFunction {},
          quoteWhenGT: AsyncFunction {},
          quoteWhenGTE: AsyncFunction {},
          quoteWhenLT: AsyncFunction {},
          quoteWhenLTE: AsyncFunction {},
          setPrice: Function setPrice {},
        },
        vaultFactory: Object @Alleged: VaultDirector machine {},
      }
    ℹ @@ schedule task for:3, currently: 0 @@
    ℹ @@ tick:1 @@
    ℹ @@ tick:2 @@
    ℹ && running a task scheduled for 2. &&
    ℹ @@ schedule task for:4, currently: 2 @@
    ℹ @@ tick:3 @@
    ℹ && running a task scheduled for 3. &&
    ℹ @@ schedule task for:6, currently: 3 @@
    ℹ @@ tick:4 @@
    ℹ && running a task scheduled for 4. &&
    ℹ @@ schedule task for:6, currently: 4 @@
    ℹ @@ tick:5 @@
    ℹ @@ tick:6 @@
    ℹ && running a task scheduled for 6. &&
    ℹ && running a task scheduled for 6. &&
    ℹ @@ schedule task for:8, currently: 6 @@
    ℹ @@ schedule task for:9, currently: 6 @@
    ℹ @@ tick:7 @@
    ℹ @@ tick:8 @@
    ℹ && running a task scheduled for 8. &&
    ℹ @@ schedule task for:10, currently: 8 @@
    ℹ @@ tick:9 @@
    ℹ && running a task scheduled for 9. &&
    ℹ ----- TestST.4  6 AMM sell {
        give: {
          brand: Object @Alleged: aEth brand {
            getAllegedName: Function getAllegedName {},
            getDisplayInfo: Function getDisplayInfo {},
            isMyIssuer: Function isMyIssuer {},
          },
          value: 8685300000n,
        },
        optStopAfter: undefined,
        want: {
          brand: Object @Alleged: aEth brand {
            getAllegedName: Function getAllegedName {},
            getDisplayInfo: Function getDisplayInfo {},
            isMyIssuer: Function isMyIssuer {},
          },
          value: 13500000000n,
        },
      }

  Rejected promise returned by test. Reason:

  Error {
    message: 'Seat ("[Alleged: zcfSeat]") was already an argument to reallocate',
  }

  ─

  1 test failed
error Command failed with exit code 1.